Temaskaming/Controllers/FAQController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Temiskaming.Models;

namespace Temiskaming.Controllers
{
    public class FAQController : Controller
    {

        FAQClass objFAQ = new FAQClass();




        public ActionResult Index(string searchString)
        {
          
         
            

            //REFERENCE http://stackoverflow.com/questions/5374481/like-operator-in-linq
            //how to search within the table if the question contains these value narrow it down 
            var Fa = from q in objFAQ.getFAQ() select q; 

            if(!string.IsNullOrEmpty(searchString))
            {
                Fa = Fa.Where(q => q.Question.Contains(searchString));
            }
            return View(Fa);
        }


        //Admin page , will hold links to insert, update, delete
        [Authorize(Roles = "Admin")]
        public ActionResult FAQAdmin()
        {
            ViewBag.Group = "Admin";
            var Fa = objFAQ.getFAQ();
            if (Fa == null)
            {
                return View("FAQAdmin");
            }
            else
            {
                return View(Fa);
            }
        }


        //insert
        [Authorize(Roles = "Admin")]
        public ActionResult FAQInsert()
        {
            ViewBag.Group = "Admin";
            return View();
        }


        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult FAQInsert(FAQ fa)
        {

            ViewBag.Group = "Admin";

            if (ModelState.IsValid)
            {
                try
                {
                    objFAQ.commitInsert(fa);
                    return RedirectToAction("FAQAdmin");
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }
        //end of insert

        //update 
        [Authorize(Roles = "Admin")]
        public ActionResult FAQUpdate(int id)
        {
            ViewBag.Group = "Admin";
            var fa = objFAQ.getFAQByID(id);
            if (fa == null)
            {
                return View("Not Found");
            }
            else
            {
                return View(fa);
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult FAQUpdate(int id, FAQ fa)
        {

            ViewBag.Group = "Admin";

            if (ModelState.IsValid)
            {
                try
                {
                    objFAQ.commitUpdate(id, fa.Question, fa.Answer);
                    return RedirectToAction("FAQAdmin");
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }
        //end of updatw

        //start delete
        [Authorize(Roles = "Admin")]
        public ActionResult FAQDelete(int id)
        {
            ViewBag.Group = "Admin";

            var fa = objFAQ.getFAQByID(id);
            if (fa == null)
            {
                return View("FAQAdmin");
            }
            else
            {
                return View(fa);
            }
        }


        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult FAQDelete(int id, FAQ fa)
        {

            ViewBag.Group = "Admin";
            try
            {
                objFAQ.commitDelete(id);
                return RedirectToAction("FAQAdmin");
            }
            catch
            {
                return View();
            }
        }
        //end of delete

    }
}

Temaskaming/Views/FAQ/FAQAdmin.cshtml
@model IEnumerable<Temiskaming.Models.FAQ>


@{
    ViewBag.Title = "FAQAdmin";
}

<h2>FAQ Admin</h2>
<div>
<h3>@Html.ActionLink("Add New Question and Answer", "FAQInsert", "FAQ")</h3>
</div>
<div>
    @foreach(var x in Model)
    {
        <table>
            <tr>
                <th>
                    <p>Question</p>
                </th>
                <th>
                    <p>Answer</p>
                </th>
            </tr>
            <tr>
       <td> @Html.DisplayFor(model => x.Question)
       </td> 
                <td>@Html.DisplayFor(model => x.Answer)</td>
                <td>
                    @Html.ActionLink("Update", "FAQUpdate", new { Id = x.Id })
                </td>

                <td>
                    @Html.ActionLink("Delete", "FAQDelete", new { Id = x.Id })
                </td>
                </tr>
            
               
           
    </table>
            
            }
</div>

Temaskaming/Views/FAQ/FAQDelete.cshtml
@model Temiskaming.Models.FAQ

@{
    ViewBag.Title = "FAQDelete";
}

<h2>FAQ Delete</h2>

<p>Are You sure you want to delete this question and answer?</p>
@using (Html.BeginForm())
{
    <input type="submit" value="Delete"/>
    @Html.ActionLink("Back", "FAQAdmin", "FAQ")
}

Temaskaming/Views/FAQ/FAQInsert.cshtml
@model Temiskaming.Models.FAQ

@{
    ViewBag.Title = "InsertFAQ";
}

<h2>InsertFAQ</h2>

@using (Html.BeginForm())
{

    <div>
        @Html.LabelFor(model => model.Question)
        @Html.TextAreaFor(model => model.Question)
        @Html.ValidationMessageFor(model => model.Question, "*")
        
    
    </div>
    <div>
        @Html.LabelFor(model => model.Answer)
        @Html.TextAreaFor(model => model.Answer)
        @Html.ValidationMessageFor(model => model.Answer, "*")
    </div>
    <div>
        <input type="submit" value="Enter" /> @Html.ActionLink("Back", "FAQAdmin", "FAQ")
    </div>
}  
    
    @section Scripts{
        @Scripts.Render("~/bundles/jqueryval")
}

Temaskaming/Views/FAQ/FAQUpdate.cshtml
@model Temiskaming.Models.FAQ

@{
    ViewBag.Title = "FAQUpdate";
}

<h2>FAQ Update</h2>

@using(Html.BeginForm())
{
    <div>
    @Html.HiddenFor(x=>x.Id)<!-- Hide ID-->
    
    </div>
    <div>
        <p>Question: </p>
    @Html.TextBoxFor(x=>x.Question)<!--Question TextBox -->
    @Html.ValidationMessageFor(x=>x.Question) <!---Valdiation message if -->
    </div>
    <div>
        <p>Answer: </p>
        @Html.TextBoxFor(x=>x.Answer)<!-- Answer Textbox-->
        @Html.ValidationMessageFor(x=>x.Answer)<!-- Validation Message -->
    </div>
    <div>
        <input type="submit" value="Update"/>
    </div>
}
    <div>
        @Html.ActionLink("Back", "FAQAdmin", "FAQ")
    </div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

Temaskaming/Views/FAQ/index.cshtml
@model IEnumerable<Temiskaming.Models.FAQ>
@{
    ViewBag.Title = "index";
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script>
    $(function () {
        $("#accordion").accordion({
            collapsible: true,
            heightStyle: "content",
            active: false
        });
    });
</script>


<h2>FAQ</h2>

<div>
    <!-- search textbox using string input to sql statement where-->
    @using (Html.BeginForm("Index", "FAQ", FormMethod.Get))
    {
        <p>
            Search: @Html.TextBox("SearchString")
            <input type="submit" value="search" />
        </p>
    }
</div>


<!--display for question-->

<div id="display">
    <div id="accordion">
        @foreach (var x in Model)
        {
            <h3>Question: @Html.DisplayFor(model => x.Question)</h3>
            <div>
                <h3>
                    Answer: @Html.DisplayFor(model => x.Answer)
                </h3>

            </div>
        }
    </div>

</div>