Temaskaming/Controllers/AlertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Temiskaming.Models;

namespace Temiskaming.Controllers
{
    public class AlertController : Controller
    {
        // properties
        alertClass alertObj = new alertClass();

        //
        // GET: /Alert/
        public ActionResult Index()                         // get : admin page, shows a list of all alerts
        {
            ViewBag.Group = "Admin";
            var allAlerts = alertObj.getAllAlerts();
            if (allAlerts == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(allAlerts);
            }

        }
                    // get : admin page, shows that alert that has been posted
        public ActionResult ActiveAlert()                   // only one alert can be active at a time
        {
            var oneAlert = alertObj.getActiveAlert();
            if (oneAlert == null)
            {
                return HttpNotFound();
            }
            else
            {
                return PartialView(oneAlert);               // returns a partial view, so that it can be renedered in the public page 
            }                                               // to be displayed on the right side column
                                                                
        }

        [Authorize(Roles = "Admin")]                        // get : admin page
        public ActionResult PublishAlert(int id)            // changes the value of the publish column to true for a particular id
        {                                                   // any alert which is already published, value is set to false.
            ViewBag.Group = "Admin";
            bool result = alertObj.publishAlert(id);
            if (result == false)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult AddAlert()          // get : admin page, shows a form to add an alert and pick a date 
        {
            ViewBag.Group = "Admin";
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult AddAlert(alert newAlert)        // post : admin page, form values are insertrd in the database
        {                                                   // the alert status by default is set to false
            newAlert.alertStatus = false;
            ViewBag.Group = "Admin";
            if (ModelState.IsValid)
            {
                try
                {
                    alertObj.commitInsertAlert(newAlert);
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }

            return View();
        }

        [Authorize(Roles = "Admin")]                
        public ActionResult UpdateAlert(int id)                      // get: admin page
        {                                                            //  shows a form to update a alert
            ViewBag.Group = "Admin";
            alert loadAlert = alertObj.getAlertByID(id);
            if (loadAlert == null)
            {
                return View();
            }
            else
            {
                return View(loadAlert);
            }
        }

        [Authorize(Roles = "Admin")]                                // post : admin page
        [HttpPost]                                                                      
        public ActionResult UpdateAlert(int id, alert updAlert)       // form values are sent to db to be updated
        {
            ViewBag.Group = "Admin";
            if (ModelState.IsValid)
            {
                try
                {
                    alertObj.commitUpdateAlert(id, updAlert.alertTitle, updAlert.alertLevel, updAlert.alertDescription, (DateTime)updAlert.alertTimeline);
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }

            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult DeleteAlert(int id)                 // get : admin page
        {                                                       // shows the record that has been requested to be deleted
            ViewBag.Group = "Admin";
            alert loadAlert = alertObj.getAlertByID(id);
            if (loadAlert == null)
            {
                return View();
            }
            else
            {
                TempData["id"] = id;
                return View(loadAlert);
            }
         
        }


        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult ConfirmDeleteAlert()        // post : admin page
        {                                               // when admin confirms the deletion, record is deleted from db
            int id = (int)TempData["id"];
            ViewBag.Group = "Admin";
            if (id > 0)
            {
                try
                {
                    alertObj.commitDeleteAlert(id);
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }

            return View();
        }
    }
}

Temaskaming/Views/Alert/ActiveAlert.cshtml
@model Temiskaming.Models.alert

@{

    DateTime expirydate = (DateTime)@Model.alertTimeline;

    var showTime = expirydate - @DateTime.Now;

}

<div id="alertDiv">

    <h3>@Model.alertTitle</h3>
    <p>
        @Model.alertDescription <strong>
        is for the next

        @if (@showTime.Days > 0)
        {@showTime.Days } Days
        @showTime.Hours hours
    </strong>
    </p>
    <p>@Model.alertLevel</p>
</div>


<script>

</script>

Temaskaming/Views/Alert/AddAlert.cshtml
@model Temiskaming.Models.alert

@{
    ViewBag.Title = "AddAlert";
}

@section Scripts{

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

    <link rel="stylesheet" href="~/Content/classic.css" />
    <link rel="stylesheet" href="~/Content/classic.date.css" />
    <script type="text/javascript" src="~/Scripts/picker.js"></script>
    <script type="text/javascript" src="~/Scripts/picker.date.js"></script>

}

<h2>AddAlert</h2>

@Html.ValidationSummary()

@using (Html.BeginForm())
{
    
<br />
@Html.LabelFor(x => x.alertTitle )
@Html.TextBoxFor(x => x.alertTitle )
<br /><br />
@Html.LabelFor(x => x.alertLevel)
@Html.TextBoxFor(x => x.alertLevel)
<br /><br />
@Html.LabelFor(x => x.alertDescription)
@Html.TextAreaFor(x => x.alertDescription)
<br /><br />
@Html.LabelFor(x => x.alertTimeline)
@Html.TextBoxFor(x => x.alertTimeline, new { @class = "datepicker" })
<br /><br />  
<input type="submit"  value="ADD"/>

}

@Html.ActionLink("Back", "Index")

<script>

    @*This datepicker api is used from source : http://amsul.ca/pickadate.js/*@

    $(document).ready(function () {
        $('.datepicker').pickadate();
    });
</script>

Temaskaming/Views/Alert/DeleteAlert.cshtml
@model Temiskaming.Models.alert

@{
    ViewBag.Title = "DeleteAlert";
}

<h2>DeleteAlert</h2>

@using (@Html.BeginForm("ConfirmDeleteAlert","Alert"))
{
    @Html.LabelFor(x => x.alertTitle)
    @Html.DisplayFor(x => x.alertTitle)
    <br />
    @Html.LabelFor(x => x.alertLevel)
    @Html.DisplayFor(x => x.alertLevel)
    <br />
    @Html.LabelFor(x => x.alertDescription)
    @Html.DisplayFor(x => x.alertDescription)
    <br />
    @Html.LabelFor(x => x.alertTimeline)
    @Html.DisplayFor(x => x.alertTimeline)

    <input type="submit" value="Confirm Delete" />


}

@Html.ActionLink("Back", "Index")

Temaskaming/Views/Alert/Index.cshtml
@model IEnumerable<Temiskaming.Models.alert>

@{
    
    ViewBag.Title = "Alerts List";
}
<br />
<div id="alert">
    <button class="buttons">@Html.ActionLink("Click here to add a New Alert", "AddAlert")</button>
    <br /><br />

    <h2>All alerts</h2>

    @foreach (var record in Model)
    {
        <h3>@record.alertTitle</h3>
        <p>@Html.DisplayFor(m => record.alertDescription) <strong>@Html.DisplayFor(m => record.alertTimeline)</strong></p>
        <p>@Html.DisplayFor(m => record.alertLevel) </p>
        <p>
            <strong>
                @if (record.alertStatus.Value == true)
                {<span>Its active</span>}
                else
                {<span>Its de-active</span>}
            </strong>
        </p>
        <br />
        <button class="button"> @Html.ActionLink("Update", "UpdateAlert", new { id = record.alertId }) </button>
        <button class="button"> @Html.ActionLink("Delete", "DeleteAlert", new { id = record.alertId }) </button>
        <button class="button"> @Html.ActionLink("Publish", "PublishAlert", new { id = record.alertId }) </button>
        <br /><br />
    }
</div>

Temaskaming/Views/Alert/UpdateAlert.cshtml
@model Temiskaming.Models.alert

@{
    ViewBag.Title = "UpdateAlert";
}

@section Scripts{

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

<link rel="stylesheet" href="~/Content/classic.css" />
<link rel="stylesheet" href="~/Content/classic.date.css" />
<script type="text/javascript" src="~/Scripts/picker.js"></script>
<script type="text/javascript" src="~/Scripts/picker.date.js"></script>

}

<link rel="stylesheet" href="../Content/themes/ashwin.css" />
<div id="update_alert">

    <h2>Update Alert</h2>
    
    @using (@Html.BeginForm())
    {
        @Html.LabelFor(x => x.alertTitle)
        @Html.TextBoxFor(x => x.alertTitle)
        <br />
        @Html.LabelFor(x => x.alertLevel)
        @Html.TextBoxFor(x => x.alertLevel)
        <br />
        @Html.LabelFor(x => x.alertDescription)
        @Html.TextAreaFor(x => x.alertDescription)
        <br />
        @Html.LabelFor(x => x.alertTimeline)
        @Html.TextBoxFor(x => x.alertTimeline, new { @class = "datepicker" })

        <input type="submit" value="submit" />
    }
</div>

@Html.ActionLink("Back", "Index")


<script>

    @*This datepicker api is used from source : http://amsul.ca/pickadate.js/*@

    $(document).ready(function () {
        $('.datepicker').pickadate();
    });
</script>