Temaskaming/Controllers/WaittimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Temiskaming.Models;

namespace Temiskaming.Controllers
{
    public class WaittimeController : Controller
    {
        WaittimeClass objWaittime = new WaittimeClass();

        public ActionResult Index()
        {
            ViewBag.Group = "Patients";
            List<SelectListItem> patientNumList = new List<SelectListItem>();//This creates a list of number for checking wait time of the last 5, 10, 15 patients.
            patientNumList.Add(new SelectListItem
            {Text = "5", Value = "5"});
            patientNumList.Add(new SelectListItem
            {Text = "10", Value = "10"});
            patientNumList.Add(new SelectListItem
            {Text = "15", Value = "15"});
            ViewBag.numList = patientNumList; //create a viewbag of list to pass to the view
            ViewBag.Wait_Time = Math.Round(objWaittime.GetWaitTime(5)).ToString(); //round the number to zero decimal palce to convert it to a string
            //By default, it displays the wait time for the last 5 patients.
            ViewBag.waitingPatients = objWaittime.GetWaitingPatients().ToString(); //Get the number of patients waiting
            return View();
        }

        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            ViewBag.Group = "Patients";
            List<SelectListItem> patientNumList = new List<SelectListItem>();
            patientNumList.Add(new SelectListItem { Text = "5", Value = "5" });
            patientNumList.Add(new SelectListItem { Text = "10", Value = "10" });
            patientNumList.Add(new SelectListItem { Text = "15", Value = "15" });
            ViewBag.numList = patientNumList;
            int numPatient = Int32.Parse(form["NumPatients"]);
            ViewBag.PatientNumber = numPatient;
            ViewBag.Wait_Time = Math.Round(objWaittime.GetWaitTime(numPatient), 0).ToString(); //Pass the number of last patients to the function GetWaitTime to get the approximate wait time.
            ViewBag.waitingPatients = objWaittime.GetWaitingPatients().ToString();
            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult admin()
        {
            ViewBag.Group = "Admin";
            var patients = objWaittime.GetPatients(); //Gets all the patients' info
            return View(patients);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult update(int id)
        {
            ViewBag.Group = "Admin";
            var patient = objWaittime.GetPatientByID(id); //display a patient's info
            return View(patient);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult update(int id, waittime patient)
        {
            ViewBag.Group = "Admin";
            if (ModelState.IsValid)
            {
                try
                {
                    objWaittime.PatientUpdate(id, patient.name, patient.time_admit, patient.time_doctor); //update the patient's info
                    return RedirectToAction("admin");
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult delete(int id)
        {
            ViewBag.Group = "Admin";
            var patient = objWaittime.GetPatientByID(id);
            if (patient == null)
            {
                return View("NotFound");
            }
            else
            {
                return View(patient);
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult delete(int id, waittime patient)
        {
            ViewBag.Group = "Admin";
            try
            {
                objWaittime.PatientDelete(id);
                return RedirectToAction("admin");
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult create()
        {
            ViewBag.Group = "Admin";
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult create(waittime patient)
        {
            ViewBag.Group = "Admin";
            if (ModelState.IsValid)
            {
                try
                {
                    objWaittime.PatientInsert(patient);
                    return RedirectToAction("admin");
                }
                catch
                {
                    return View();
                }
            }
            else
            {
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult NotFound()
        {
            ViewBag.Group = "Admin";
            return View();
        }

    }
}

Temaskaming/Views/Waittime/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Emergency Room Wait Time</h2>

@using (Html.BeginForm("Index", "Waittime", FormMethod.Post))
{
    <p>Get the average wait time for the last @Html.DropDownList("NumPatients", new SelectList(ViewBag.numList, "Value", "Text")) patients. <input type="submit" value="Submit" /></p> 
}

<p>The approximate wait time is @ViewBag.Wait_Time minutes.</p>

<p>There are currently @ViewBag.waitingPatients patient(s) waiting in the emergency room.</p>

Temaskaming/Views/Waittime/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
}

<h2>NotFound</h2>

Temaskaming/Views/Waittime/admin.cshtml
@using Temiskaming.Models
@model IEnumerable<Temiskaming.Models.waittime>

@*@{ var objwaittime = new WaittimeClass();}*@

@{
    ViewBag.Title = "admin";
}

<h2>Wait Time Admin Page</h2>
@Html.ActionLink("Create New Patient", "create")
<table>
    <tr>
        <td>Name</td>
        <td>Time of Admission</td>
        <td>Time of Seeing a Doctor</td>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.name</td>
            <td>@x.time_admit</td>
            <td>@x.time_doctor</td>
            <td>@Html.ActionLink("Edit", "update", new {id = x.id})</td>
            <td>@Html.ActionLink("Delete", "delete", new
                {
                    id = x.id
                })</td>
        </tr>
    }
</table>

Temaskaming/Views/Waittime/create.cshtml
@model Temiskaming.Models.waittime

@{
    ViewBag.Title = "create";
}


@{
    DateTime currentTime = DateTime.Now; //create a variable that holds the current time.
}
<h2>create</h2>
<p>It is now @currentTime</p>
@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <br />
    @Html.LabelFor(x=>x.name)
    @Html.TextBoxFor(x=>x.name)
    @Html.ValidationMessageFor(x=>x.name)
    <br/>
    @Html.HiddenFor(x=>x.time_admit, new {@Value = currentTime}) //create a hidden field whose value is the current time
    <br/>
    
    <input type="submit" value="Create"/>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

Temaskaming/Views/Waittime/delete.cshtml
@model Temiskaming.Models.waittime

@{
    ViewBag.Title = "delete";
}

<h2>Confirm to patient @Model.name?</h2>

@using (Html.BeginForm())
{
    <input type="submit" value="Yes"/>
    @Html.ActionLink("Cancel", "admin")
}

Temaskaming/Views/Waittime/update.cshtml
@using Temiskaming.Models

@model Temiskaming.Models.waittime

@{
    ViewBag.Title = "update";
}

@{
    DateTime currentTime = DateTime.Now;
}


<h2>update</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <br/>
    @Html.HiddenFor(x=>x.id)
    @Html.LabelFor(x=>x.name)
    @Html.TextBoxFor(x=>x.name)
    <br/>
    @Html.LabelFor(x=>x.time_admit)
    @Html.TextBoxFor(x=>x.time_admit)
    @Html.ValidationMessageFor(x=>x.time_admit)
    <br/>
    @Html.LabelFor(x=>x.time_doctor)
    @Html.TextBoxFor(x=>x.time_doctor, new {@Value = currentTime})
    @Html.ValidationMessageFor(x=>x.time_doctor)
    <br/><br/>
    <input type="submit" value="Update"/>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}