Temaskaming/Controllers/AdminJobPostingsController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Temiskaming.Models;

// controller which inserts, updates, and deletes data from tables for job applications and job postings
namespace Temiskaming.Controllers
{
    public class AdminJobPostingsController : Controller
    {
        linqjobsClass objJob = new linqjobsClass();

        // action result that shows all job postings
        public ActionResult AdminShowJobPostings()
        {
            ViewBag.Group = "Admin";
            var jobpostings = objJob.getJobs();
            return View(jobpostings);
        }

        // action result which shows all job applications
        public ActionResult ShowJobApp()
        {
            ViewBag.Group = "Admin";
            var jobapps = objJob.getApplications();
            return View(jobapps);
        }

        //action result which shows the form for new job posting to be created
        public ActionResult NewJob()
        {
            ViewBag.Group = "Admin";
            return View();
        }

        // action result which on post inserts new job posting into database
        [HttpPost]
        public ActionResult NewJob(job validjob)
        {
            ViewBag.Group = "Admin";
            if (ModelState.IsValid)
            {
                try
                {
                    objJob.commitInsert(validjob);
                    return RedirectToAction("AdminShowJobPostings");
                }
                catch
                {
                    return View();
                }
            }
            else return View();
        }

        //action result which shows selected job posting to be updated
        public ActionResult ViewJobDetails(int id)
        {
            ViewBag.Group = "Admin";
            var job = objJob.getJobsById(id);
            if (job == null)
            {
                return View("NotFound");
            }
            else
            {
                return View(job);
            }
        }

        // action result which on post updates job posting if the data is valid
        [HttpPost]
        public ActionResult ViewJobDetails(int id, job validjob)
        {
            ViewBag.Group = "Admin";
            if (ModelState.IsValid)
            {
                try
                {
                    objJob.commitUpdatejob(id, validjob.jobtitle, validjob.jobdescr, validjob.posteddate.Value, validjob.qualifications, validjob.duration);
                    return RedirectToAction("AdminShowJobPostings");
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }

        //action result which on post updates selected job application if the data is valid
        [HttpPost]
        public ActionResult ViewDetailsJobApp(int id, jobapplication validjobapp)
        {
            ViewBag.Group = "Admin";
            if (ModelState.IsValid)
            {
                try
                {
                    objJob.commitUpdateApp(id, validjobapp.anotes, validjobapp.jobtitle, validjobapp.aname, validjobapp.aphone, validjobapp.aemail, validjobapp.aresume, validjobapp.acoverletter);
                    return RedirectToAction("ShowJobApp");
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }

        //action result which shows selected job application
        public ActionResult ViewDetailsJobApp(int id)
        {
            ViewBag.Group = "Admin";
            //setting variables in the viewbag to be used later in hidden fields which don't change when updating the job application
            var jobapplication = objJob.getAppsById(id);
            ViewBag.jobtitle = jobapplication.jobtitle;
            ViewBag.aname = jobapplication.aname;
            ViewBag.aphone = jobapplication.aphone;
            ViewBag.aemail = jobapplication.aemail;
            ViewBag.aresume = jobapplication.aresume;
            ViewBag.acoverletter = jobapplication.acoverletter;

            if (jobapplication == null)
            {
                return View("NotFound");
            }
            else
            {
                return View(jobapplication);
            }
        }

        // action method which deletes job posting from the database based on id 
        public ActionResult DeleteJob(int id)
        {
            ViewBag.Group = "Admin";
            var job = objJob.getJobsById(id);
            if (job == null)
            {
                return View("NotFound");
            }
            else
            {
                objJob.commitDelete(id);
                return RedirectToAction("AdminShowJobPostings");
            }
        }

        // action method which deletes job application from the database based on id 
        public ActionResult DeleteApp(int id)
        {
            ViewBag.Group = "Admin";
            var app = objJob.getAppsById(id);
            if (app == null)
            {
                return View("NotFound");
            }
            else
            {
                objJob.commitAppDelete(id);
                return RedirectToAction("ShowJobApp");
            }
        }

    }
}

Temaskaming/Views/AdminJobPostings/AdminShowJobPostings.cshtml
@model IEnumerable<Temiskaming.Models.job>

@{
    ViewBag.Title = "AdminShowJobPostings";
}
@*link to show job applications*@
@Html.ActionLink("Show job applications", "ShowJobApp", "AdminJobPostings")
<h2>View and update Job Postings</h2>
@*table to show job descriptions and options to update them*@
<table class="admin_job">
    <tr>
        <th>Job Title</th>
        <th>Job Description</th>
        <th>Option 1</th>
        <th>Option 2</th>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td colspan="2">@Html.ActionLink("Create new listing", "NewJob", "AdminJobPostings")</td>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(model => x.jobtitle)
            </td>
            <td>
                @Html.DisplayFor(model => x.jobdescr)
            </td>
            <td>
                @Html.ActionLink("View details/Update", "ViewJobDetails", new { id = x.Id })
            </td>
            <td>
                @Html.ActionLink("Delete", "DeleteJob", new { id = x.Id })
            </td>
        </tr>
    }
</table>

Temaskaming/Views/AdminJobPostings/NewJob.cshtml
@model Temiskaming.Models.jobValidation

@{
    ViewBag.Title = "Insert new job posting";
}

<h2>Insert New Job Posting</h2>
@Html.ActionLink("Go back to all Job Postings", "AdminShowJobPostings", "AdminJobPostings")

@* form with controls and validation for them which adds new job posting *@
@using (Html.BeginForm())
{
    <table class="job_post_form">
        <tr>
            @*label, textbox and validation message for jobtitle *@
            <th>
                @Html.LabelFor(model => model.jobtitle)
            </th>
            <td>
                @Html.TextBoxFor(model => model.jobtitle, new { @class = "jobform" })
                @Html.ValidationMessageFor(model => model.jobtitle, "*")
            </td>
        </tr>
        <tr>
            @*label, textarea and validation message for jobdescription *@
            <th>
                @Html.LabelFor(model => model.jobdescr)
            </th>
            <td>
                @Html.TextAreaFor(model => model.jobdescr)
                @Html.ValidationMessageFor(model => model.jobdescr, "*")
            </td>
        </tr>
        <tr>
            @*label, textbox and validation message for posted date *@
            <th>
                @Html.LabelFor(model => model.posteddate)
            </th>
            <td>
                @Html.TextBoxFor(model => model.posteddate, new { @class = "jobform" })
                @Html.ValidationMessageFor(model => model.posteddate, "*")
            </td>
        </tr>
        <tr>
            @*label, textbox and validation message for qualifications *@
            <th>
                @Html.LabelFor(model => model.qualifications)
            </th>
            <td>
                @Html.TextBoxFor(model => model.qualifications, new { @class = "jobform" })
                @Html.ValidationMessageFor(model => model.qualifications, "*")
            </td>
        </tr>
        <tr>
            @*label, textbox and validation message for duration *@
            <th>
                @Html.LabelFor(model => model.duration)
            </th>
            <td>
                @Html.TextBoxFor(model => model.duration, new { @class = "jobform" })
                @Html.ValidationMessageFor(model => model.duration, "*")
            </td>
        </tr>
        <tr>
            <td></td>
            <td style="text-align:right"><input type="submit" value="Create New" /></td>
        </tr>
    </table>
    @* submit button for inserting new job posting *@
    <br /> <br />
    @Html.ValidationSummary()
}
@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Temaskaming/Views/AdminJobPostings/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
}
@* link to go back to  index page *@
@Html.ActionLink("Go back to Admin for viewing job postings", "AdminShowJobPostings", "AdminJobPostings")

Temaskaming/Views/AdminJobPostings/ShowDetailsJobApp.cshtml
@model Temiskaming.Models.jobapplication

@{
    ViewBag.Title = "Details for application";
}
@Html.ActionLink("Go back to viewing applications", "ShowJobApp", "AdminJobPostings")
@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.jobtitle, new { @Value = ViewBag.jobtitle })
    @Html.HiddenFor(x => x.aname, new { @Value = ViewBag.aname })
    @Html.HiddenFor(x => x.aphone, new { @Value = ViewBag.aphone })
    @Html.HiddenFor(x => x.aemail, new { @Value = ViewBag.aemail })
    @Html.HiddenFor(x => x.aresume, new { @Value = ViewBag.aresume })
    @Html.HiddenFor(x => x.acoverletter, new { @Value = ViewBag.acoverletter })
    <table class="job_post_form">
        <tr>
            <th>
                Job Title:
            </th>
            <td>
                <span class="jobform">@Html.DisplayFor(x => x.jobtitle)</span>
            </td>
        </tr>
        <tr>
            <th>
                Applicant name:
            </th>
            <td>
                <span class="jobform">@Html.DisplayFor(x => x.aname)</span>
            </td>
        </tr>
        <tr>
            <th>
                Notes:
            </th>
            <td style="text-align:right">
                @Html.TextAreaFor(x => x.anotes, new { @class = "jobform" })
                <br /><br />
                <input type="submit" value="Update" />
                @Html.ValidationSummary()
            </td>
        </tr>
        <tr>
            <th>
                Phone:
            </th>
            <td>
                <span class="jobform">@Html.DisplayFor(x => x.aphone)</span>
            </td>
        </tr>
        <tr>
            <th>
                Email:
            </th>
            <td>
                <span class="jobform">@Html.DisplayFor(x => x.aemail)</span>
            </td>
        </tr>
        <tr>
            <th>
                Resume:
            </th>
            <td>
                <span class="jobform">@Html.DisplayFor(x => x.aresume)</span>
            </td>
        </tr>
        <tr>
            <th>
                Cover letter:
            </th>
            <td>
                <span class="jobform">@Html.DisplayFor(x => x.acoverletter)</span>
            </td>
        </tr>
    </table>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}  

Temaskaming/Views/AdminJobPostings/ShowJobApp.cshtml
@model IEnumerable<Temiskaming.Models.jobapplication>

@{
    ViewBag.Title = "AdminShowJobPostings-Applications";
}
@*action link to view job postings*@
@Html.ActionLink("Show job postings", "AdminShowJobPostings", "AdminJobPostings")
<h2>View and update Job Applications</h2>
<br />
@*table to show job applications*@
<table class="admin_job">
    <tr>
        <th>Job Title</th>
        <th>Applicant Name</th>
        <th>Phone</th>
        <th>Notes</th>
        <th>Option 1</th>
        <th>Option 2</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(model => x.jobtitle)
            </td>
            <td>
                @Html.DisplayFor(model => x.aname)
            </td>
            <td>
                @Html.DisplayFor(model => x.aphone)
            </td>
            <td>
                @Html.DisplayFor(model => x.anotes)
            </td>
            <td>
                @Html.ActionLink("View details/Update", "ViewDetailsJobApp", new { id = x.Id })
            </td>
            <td>
                @Html.ActionLink("Delete", "DeleteApp", new { id = x.Id })
            </td>
        </tr>
    }
</table>

Temaskaming/Views/AdminJobPostings/ViewDetailsJobApp.cshtml
@model Temiskaming.Models.jobapplication

@{
    ViewBag.Title = "Details for application";
}
@*link to view job applications*@
@Html.ActionLink("Go back to viewing applications", "ShowJobApp", "AdminJobPostings")
@using (Html.BeginForm())
{   
    @* hidden fields for variables that will not be updated *@
    @Html.HiddenFor(x => x.jobtitle, new { @Value = ViewBag.jobtitle })
    @Html.HiddenFor(x => x.aname, new { @Value = ViewBag.aname })
    @Html.HiddenFor(x => x.aphone, new { @Value = ViewBag.aphone })
    @Html.HiddenFor(x => x.aemail, new { @Value = ViewBag.aemail })
    @Html.HiddenFor(x => x.aresume, new { @Value = ViewBag.aresume })
    @Html.HiddenFor(x => x.acoverletter, new { @Value = ViewBag.acoverletter })
    <table class="job_post_form">
        <tr>
            <th>
                Job Title:
            </th>
            <td>
                <span class="jobform">@Html.DisplayFor(x => x.jobtitle)</span>
            </td>
        </tr>
        <tr>
            <th>
                Applicant name:
            </th>
            <td>
                <span class="jobform">@Html.DisplayFor(x => x.aname)</span>
            </td>
        </tr>
        <tr>
            <th>
                Notes:
            </th>
            <td style="text-align:right">
                @Html.TextAreaFor(x => x.anotes, new { @class = "jobform" })
                <br /><br />
                <input type="submit" value="Update" />
                @Html.ValidationSummary()
            </td>
        </tr>
        <tr>
            <th>
                Phone:
            </th>
            <td>
                <span class="jobform">@Html.DisplayFor(x => x.aphone)</span>
            </td>
        </tr>
        <tr>
            <th>
                Email:
            </th>
            <td>
                <span class="jobform">@Html.DisplayFor(x => x.aemail)</span>
            </td>
        </tr>
        <tr>
            <th>
                Resume:
            </th>
            <td>
                <span class="jobform">@Html.DisplayFor(x => x.aresume)</span>
            </td>
        </tr>
        <tr>
            <th>
                Cover letter:
            </th>
            <td>
                <span class="jobform">@Html.DisplayFor(x => x.acoverletter)</span>
            </td>
        </tr>
    </table>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}  

Temaskaming/Views/AdminJobPostings/ViewJobDetails.cshtml
@model Temiskaming.Models.job
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<h2>Update Job Posting</h2>
@*action link to view job postings*@
@Html.ActionLink("Go back to viewing job postings", "AdminShowJobPostings", "AdminJobPostings")
@using (Html.BeginForm())
{   
    @*table to show job postings*@
    <table class="job_post_form">
        <tr>
            @*label, textbox and validation for jobtitle*@
            <th>
                @Html.LabelFor(x => x.jobtitle)
            </th>
            <td>
                @Html.TextBoxFor(x => x.jobtitle, new { @class = "jobform" })
                @Html.ValidationMessageFor(x => x.jobtitle, "*")

            </td>
        </tr>
        <tr>
            @*label, textarea and validation for jobdescription*@
            <th>
                @Html.LabelFor(x => x.jobdescr)
            </th>
            <td>
                @Html.TextAreaFor(x => x.jobdescr)
                @Html.ValidationMessageFor(x => x.jobdescr, "*")
            </td>
        </tr>
        <tr>
            @*label, textbox and validation for posted date*@
            <th>
                @Html.LabelFor(x => x.posteddate)
            </th>
            <td>
                @Html.TextBoxFor(x => x.posteddate, new { @class = "jobform" })
                @Html.ValidationMessageFor(x => x.posteddate, "*")
            </td>
        </tr>
        <tr>
            @*label, textbox and validation for qualifications*@
            <th>
                @Html.LabelFor(x => x.qualifications)
            </th>
            <td>
                @Html.TextBoxFor(x => x.qualifications, new { @class = "jobform" })
                @Html.ValidationMessageFor(x => x.qualifications, "*")
            </td>
        </tr>
        <tr>
            @*label, textbox and validation for duration*@
            <th>
                @Html.LabelFor(x => x.duration)
            </th>
            <td>
                @Html.TextBoxFor(x => x.duration, new { @class = "jobform" })
                @Html.ValidationMessageFor(x => x.duration, "*")
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Update Job Posting" />
            </td>
        </tr>
    </table>
    @Html.ValidationSummary()
}